---
- name: install epel-release repository on RHEL
  yum:
    name: epel-release
    state: installed
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: ensure fail2ban is installed
  package:
    name: fail2ban
    state: present
  notify: restart fail2ban

- name: set jail configuration
  template:
    src: jail.conf.j2
    dest: '/etc/fail2ban/jail.local'
    mode: 0644
  notify: restart fail2ban

- name: ensure fail2ban service is enabled
  service:
    name: fail2ban
    enabled: True