---
- name: update firewall on debian-based machine
  shell: iptables-save > /etc/iptables/rules.v4
  when: ansible_pkg_mgr == "apt"

- name: restart fail2ban
  systemd:
    daemon_reload: yes
    name: fail2ban
    state: restarted
